AdfUIComponents.createComponentClass("AdfRichPanelBox",{componentType:"oracle.adf.RichPanelBox",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},"disclosureListener",{name:"disclosed",type:"Boolean","default":!0},{name:"immediate",type:"Boolean","default":!1},{name:"helpTopicId",type:"String"},{name:"persist",type:"Array"},{name:"dontPersist",type:"Array"},
{name:"showDisclosure",type:"Boolean","default":!0},{name:"handleDisclosure",type:"String","default":"server"},{name:"maximized",type:"Boolean","default":!1},{name:"showMaximize",type:"String","default":"auto"},"maximizeListener",{name:"contentDelivery",type:"String","default":"lazyUncached"},{name:"text",type:"String"},{name:"type",type:"String","default":"default"},{name:"showHeader",type:"String","default":"ifNeeded"},{name:"ramp",type:"String","default":"core"},{name:"background",type:"String",
"default":"default"},{name:"icon",type:"String"},{name:"contentStyle",type:"String"},{name:"titleHalign",type:"String","default":"start"}],eventNames:["disclosure"],superclass:AdfUIPanel});

AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlPanelBoxPeer",!1);AdfDhtmlPanelBoxPeer.DISCLOSURE_SUB_ID="_afrDscl";AdfDhtmlPanelBoxPeer._INNER_SD_PEER=AdfRichUIPeer.createInnerPeerClassWithSubId(AdfDhtmlShowDisclosurePeer,"InnerPBShowDetailPeer",AdfDhtmlPanelBoxPeer.DISCLOSURE_SUB_ID);InnerPBShowDetailPeer.InitSubclass=function(){AdfDhtmlTogglePeer.Config(this,{toggledStyleClass:"af|panelBox::disclosed-icon-style",untoggledStyleClass:"af|panelBox::undisclosed-icon-style"})};
InnerPBShowDetailPeer.prototype.HandleClientSideToggle=function(a){return this.outerThis.GetContentDomElement()&&InnerPBShowDetailPeer.superclass.HandleClientSideToggle.call(this,a)?(this.outerThis.__handleClientSideDisclosure(a),!0):!1};
InnerPBShowDetailPeer.prototype.EventPropagatesToServer=function(a){var b=InnerPBShowDetailPeer.superclass.EventPropagatesToServer.call(this);if(!1==b){var d=this.outerThis.getComponent();if("lazy"===d.getPropertyValue("contentDelivery")&&null==this.outerThis.GetContentDomElement()||!1==a&&AdfPage.PAGE.getDirtyStateService().hasDirtyData(d))b=!0}return b};AdfDhtmlPanelBoxPeer.MAXIMIZE_SUB_ID="_afrMax";
AdfDhtmlPanelBoxPeer._INNER_MAXIMIZE_PEER=AdfRichUIPeer.createInnerPeerClassWithSubId(AdfDhtmlMaximizePeer,"InnerPBMaximizePeer",AdfDhtmlPanelBoxPeer.MAXIMIZE_SUB_ID);InnerPBMaximizePeer.InitSubclass=function(){AdfDhtmlTogglePeer.Config(this,{toggledStyleClass:"af|panelBox::maximized-icon-style",untoggledStyleClass:"af|panelBox::unmaximized-icon-style"})};
InnerPBMaximizePeer.prototype.HandleClientSideToggle=function(a){var b=this.outerThis,d=b.GetContentDomElement();return d&&InnerPBMaximizePeer.superclass.HandleClientSideToggle.call(this,a)?(b.__handleClientSideMaximize(b.getDomElement(),d,a),!0):!1};InnerPBMaximizePeer.prototype.ComponentMaximizedChanged=function(a,b,d,e){b=InnerPBMaximizePeer.superclass.ComponentMaximizedChanged.call(this,a,b,d,e);d&&a.setDisclosed(!0);return b};InnerPBMaximizePeer.prototype.EventPropagatesToServer=function(a){return!this.outerThis.GetContentDomElement()};
AdfDhtmlPanelBoxPeer.InitSubclass=function(){AdfObject.ensureClassInitialization(AdfRichPanelBox);AdfRichUIPeer.addComponentPropertyChanges(this,AdfRichPanelBox.DISCLOSED,AdfRichPanelBox.MAXIMIZED);AdfRichUIPeer.addComponentEventHandlers(this,AdfUIInputEvent.CLICK_EVENT_TYPE,AdfUIInputEvent.KEY_UP_EVENT_TYPE,AdfDisclosureEvent.EVENT_TYPE,AdfMaximizeEvent.EVENT_TYPE);this._DRAG_RECOGNIZER=new AdfPanelBoxDragRecognizer};
AdfDhtmlPanelBoxPeer.prototype.Init=function(a){AdfDhtmlPanelBoxPeer.superclass.Init.call(this,a);var b=a.getClientId(),d=AdfRichUIPeer.CreateSubId(b,AdfDhtmlPanelBoxPeer.DISCLOSURE_SUB_ID);AdfAgent.AGENT.getElementById(d)&&(this._disclosurePeer=this.CreateDisclosurePeer(a));b=AdfRichUIPeer.CreateSubId(b,AdfDhtmlPanelBoxPeer.MAXIMIZE_SUB_ID);AdfAgent.AGENT.getElementById(b)&&(this._maximizePeer=this.CreateMaximizePeer(a));this._ignoreUpAndDownArrowKey="false"==AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelBox-tr-disclose-with-up-down-arrow")};
AdfDhtmlPanelBoxPeer.prototype.CreateDisclosurePeer=function(a){return new AdfDhtmlPanelBoxPeer._INNER_SD_PEER(a,this)};AdfDhtmlPanelBoxPeer.prototype.CreateMaximizePeer=function(a){return new AdfDhtmlPanelBoxPeer._INNER_MAXIMIZE_PEER(a,this)};AdfDhtmlPanelBoxPeer.prototype.initialize=function(a){var b=this._disclosurePeer;b&&b.initialize(a);(b=this._maximizePeer)&&b.initialize(a);AdfDhtmlPanelBoxPeer.superclass.initialize.call(this,a)};
AdfDhtmlPanelBoxPeer.prototype.InitDomElement=function(a,b){AdfDhtmlPanelBoxPeer.superclass.InitDomElement.call(this,a,b);var d=this.GetContentDomElement(b);d&&(this._checkAnimateDisclosure(a,d),this._maximizePeer&&this.__handleClientSideMaximize(b,d,a.getMaximized()))};AdfDhtmlPanelBoxPeer.prototype.GetContentDomElement=function(a){a||(a=this.getDomElement());a=AdfRichUIPeer.CreateSubId(a.id,"content");return AdfAgent.AGENT.getElementById(a)};AdfDhtmlPanelBoxPeer.prototype.GetAnimationDuration=function(){return parseInt(AdfPage.PAGE.getLookAndFeel().getSkinProperty("af|panelBox-tr-animation-duration"))};
AdfDhtmlPanelBoxPeer.prototype._checkAnimateDisclosure=function(a,b){if(null!=b&&"hidden"==b.style.visibility){var d=b.style.height,d=d?parseInt(d):b.offsetHeight,e=b.ownerDocument.createElement("div");e.style.overflow="hidden";e.style.height="1px";b.parentNode.replaceChild(e,b);e.appendChild(b);b.style.visibility="visible";var f=this.GetAnimationDuration();AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_CONSTANT_SPEED,f,[{element:e,properties:{height:d}}],null,AdfDhtmlPanelBoxPeer._handleAfterDiscloseAnimate,
[e,b],a)}};AdfDhtmlPanelBoxPeer._handleAfterDiscloseAnimate=function(a){var b=a[0],d=b.parentNode;null!=d&&d.replaceChild(a[1],b)};
AdfDhtmlPanelBoxPeer.prototype._animateUndisclosure=function(a){var b=this.GetContentDomElement(),d=b.style.height;b.style.overflow="hidden";var e=this.GetAnimationDuration(),f=this.getComponent();AdfDhtmlElementAnimator.animate(AdfDhtmlElementAnimator.FRAME_METHOD_CONSTANT_SPEED,e,[{element:b,properties:{height:0}}],null,AdfDhtmlPanelBoxPeer._handleAfterUndiscloseAnimateStub,[f,a,d],f)};
AdfDhtmlPanelBoxPeer._handleAfterUndiscloseAnimateStub=function(a){var b=a[0],d=b.getPeer();null!=d&&(d.bind(b),d._handleAfterUndiscloseAnimate(a[1],a[2]))};AdfDhtmlPanelBoxPeer.prototype._handleAfterUndiscloseAnimate=function(a,b){var d=this.getComponent();if(!d.isDead()){var e=this.GetContentDomElement();null!=e&&(e.style.visibility="hidden");d.HandleEvent.call(d,a);this.__handleClientSideDisclosure(!1);e&&(d=e.style,d.display="none",d.height=b?b:"")}};
AdfDhtmlPanelBoxPeer.prototype.DispatchUncanceledComponentEvent=function(a){return AdfPage.PAGE.isAnimationEnabled()&&a.getType()==AdfDisclosureEvent.EVENT_TYPE&&!a.isExpanded()?(this._animateUndisclosure(a),!0):!1};AdfDhtmlPanelBoxPeer.prototype.HandleComponentClick=function(a){var b=this._disclosurePeer;b&&b.HandleComponentClick(a);(b=this._maximizePeer)&&b.HandleComponentClick(a)};
AdfDhtmlPanelBoxPeer.prototype.HandleComponentKeyUp=function(a){var b=this._disclosurePeer;if(b){var d=!0;this._ignoreUpAndDownArrowKey&&(d=a.getNativeEvent(),d=AdfAgent.AGENT.getKeyCode(d),d=d!=AdfKeyStroke.ARROWUP_KEY&&d!=AdfKeyStroke.ARROWDOWN_KEY);d&&b.HandleComponentKeyUp(a)}(b=this._maximizePeer)&&b.HandleComponentKeyUp(a)};AdfDhtmlPanelBoxPeer.prototype.HandleComponentDisclosure=function(a){var b=this._disclosurePeer;b&&b.HandleComponentDisclosure(a)};
AdfDhtmlPanelBoxPeer.prototype.HandleComponentMaximize=function(a){var b=this._maximizePeer;b&&b.HandleComponentMaximize(a)};AdfDhtmlPanelBoxPeer.prototype.ComponentDisclosedChanged=function(a,b,d,e){var f=this._disclosurePeer;return f?f.ComponentDisclosedChanged(a,b,d,e):!1};AdfDhtmlPanelBoxPeer.prototype.ComponentMaximizedChanged=function(a,b,d,e){var f=this._maximizePeer;return f?f.ComponentMaximizedChanged(a,b,d,e):!1};
AdfDhtmlPanelBoxPeer.prototype.__isEventForHeaderControls=function(a){var b=!1,d=this._disclosurePeer;d&&(b|=d.isEventForButton(a));(d=this._maximizePeer)&&(b|=d.isEventForButton(a));return b};AdfDhtmlPanelBoxPeer.prototype.getDefaultDragRecognizer=function(a){return AdfDhtmlPanelBoxPeer._DRAG_RECOGNIZER};
AdfDhtmlPanelBoxPeer.prototype.__handleClientSideDisclosure=function(a){var b=this.GetContentDomElement(),d=b.parentNode,e=b.style,f=AdfPage.PAGE.isAnimationEnabled();a?(f&&(e.visibility="hidden"),e.display="",d.style.display=""):f||(d.style.display="none",e.display="none");d=this.getDomElement();e=d.lastChild;f="DIV"==AdfAgent.AGENT.getNodeName(e);a?(f&&(e.style.top=""),this._checkAnimateDisclosure(this.getComponent(),b)):f&&(e.style.top=d.firstChild.clientHeight+"px")};
AdfDhtmlPanelBoxPeer.prototype.__handleClientSideMaximize=function(a,b,d){AdfAssert.assertDomElement(a);AdfAssert.assertDomElement(b);AdfAssert.assertBoolean(d);this._maximizePeer.__updateClientMaximize(a,b,d);if(a=this._disclosurePeer)if(a=a.GetButtonElement())a.style.display=d?"none":"block"};function AdfPanelBoxDragRecognizer(){this.Init()}AdfObject.createSubclass(AdfPanelBoxDragRecognizer,AdfDragRecognizer);
AdfPanelBoxDragRecognizer.prototype.prepDrag=function(a,b,d){AdfAssert.assertPrototype(b,AdfDragSource);AdfAssert.assertPrototype(d,AdfUIInputEvent);if(AdfAgent.AGENT.isDragPrepEvent(d)){var e=b.getComponent();AdfAssert.assertObject(e,"Unexpected null component.");var f=e.getPeer(),g=d.getNativeEvent();if(!f.__isEventForHeaderControls(g)&&(AdfAssert.assert(f,"Unexpected null peer."),f.bind(e),e=f.getDomElement(),e=AdfDomUtils.getFirstChildElement(e)))if(f=AdfAgent.AGENT.getNodeName(e),"TABLE"!=f&&
(e=AdfDomUtils.getFirstChildElement(e),f=AdfAgent.AGENT.getNodeName(e)),"TABLE"==f&&(f=d.getNativeEventTarget(),AdfDomUtils.isAncestorOrSelf(e,f)))return AdfPanelBoxDragRecognizer.superclass.prepDrag.apply(this,arguments)}return null};